#!/usr/bin/env node

var program = require('commander');
var tools   = require('common-tools');

program
  .version('0.0.1')
  .usage('-m 13006699866 -p passWord!')
  .option('-m, --mobile [mobile]', 'Mobile （必须填写）')
  .option('-p, --password [password]', 'Password （必须填写）')
  .option('-e, --node_env [node_env]', 'Environment: product, development, test')
  .parse(process.argv);

var mobile            = program.mobile;
var password         = program.password;
var nodeEnv          = program.node_env || "development";
process.env.NODE_ENV = nodeEnv;

if (!mobile || !password) {
  program.outputHelp();
  return;
}

if (!tools.validateTools.isChinaMobile(mobile)) {
  console.log('请输入正确的手机');
  return;
}


var reginfo = {
  mobile    : mobile,
  password : password,
  account_type: 9
};


var co             = require('co');
var accountService = require('./services/Account');
var ezmysql        = require('ezway2mysql');
var config         = require('./config');
ezmysql.connect(config.mysql);


console.log("现在开始创建用户..");


var xco = co(function *() {
  var res = yield accountService.register(reginfo);
  console.log(res);
  console.log("你创建的超级管理员帐号是：");
  console.log(`用户名： ${mobile}`);
  console.log(`密码：${password}`);
  console.log("现在请按 ^C 退出。");

}).catch(function (reson) {
  console.log(reson);
  console.log("现在请按 ^C 退出。");
});