#!/usr/bin/env node

var request = require('request');


var reginfo = {
  mobile      : '13006699861',
  password    : '111111',
  account_type: 9
};
//
// request.post('http://localhost:3000/open/account/register',
//   {
//     form: reginfo
//   }, function (err, res, body) {
//     console.log(body);
//   });

// request.post('http://localhost:3000/open/account/check-passport',
//   {
//     form: {passport: '13006699865'},
//   }, function (err, res, body) {
//     console.log(body);
//   });

// request.post('http://localhost:3000/open/account/login',
//   {
//     form: {passport: '13006699866',password:'111111'},
//   }, function (err, res, body) {
//     console.log(body);
//   });

// request.post('http://localhost:3000/open/address/update',
//   {
//     form: {
//       id         : 1,
//       ticket     : 'eyJvcGVuX2lkIjoiODAwMjE3OWEtMzJjNS0xMWU2LTlhNDEtMDI0MmFjMTEwMDA0IiwiZXhwaXJlc19pbiI6MTQ2NTk4MjM5MCwic2lnbiI6ImE5N2I5YmEzY2M1OWQ3MGVjY2JiYTIyYTgwYmNlNjE4YmI4ZmIyODAyY2ZmMDBlZWY1NGEwMGQ1MmYyZDIwYzYifQ==',
//       district_id: 875,
//       cnee       : '张三',
//       address    : "查查了某某ID阿莎",
//       tel1       : '123444',
//       postcode   : '2345522'
//
//     },
//   }, function (err, res, body) {
//     console.log(body);
//   });

// request.post('http://localhost:3000/open/address/delete',
//   {
//     form: {
//       id         : 3,
//       ticket     : 'eyJvcGVuX2lkIjoiODAwMjE3OWEtMzJjNS0xMWU2LTlhNDEtMDI0MmFjMTEwMDA0IiwiZXhwaXJlc19pbiI6MTQ2NTk4MjM5MCwic2lnbiI6ImE5N2I5YmEzY2M1OWQ3MGVjY2JiYTIyYTgwYmNlNjE4YmI4ZmIyODAyY2ZmMDBlZWY1NGEwMGQ1MmYyZDIwYzYifQ==',
//       district_id: 875,
//       cnee       : '张三',
//       address    : "查查了某某ID阿莎",
//       tel1       : '123444',
//       postcode   : '2345522'
//
//     },
//   }, function (err, res, body) {
//     console.log(body);
//   });


request.post('http://localhost:3000/open/address/set-default',
  {
    form: {
      id         : 4,
      ticket     : 'eyJvcGVuX2lkIjoiODAwMjE3OWEtMzJjNS0xMWU2LTlhNDEtMDI0MmFjMTEwMDA0IiwiZXhwaXJlc19pbiI6MTQ2NTk4MjM5MCwic2lnbiI6ImE5N2I5YmEzY2M1OWQ3MGVjY2JiYTIyYTgwYmNlNjE4YmI4ZmIyODAyY2ZmMDBlZWY1NGEwMGQ1MmYyZDIwYzYifQ==',
      

    },
  }, function (err, res, body) {
    console.log(body);
  });