#!/usr/bin/env node

var program = require('commander');
var tools   = require('common-tools');

program
  .version('0.0.1')
  .usage('-m cloudbeer@gmail.com -p passWord!')
  .option('-m, --email [email]', 'Email （必须填写）')
  .option('-p, --password [password]', 'Password （必须填写）')
  .option('-e, --node_env [node_env]', 'Environment: product, development, test')
  .parse(process.argv);

var email            = program.email;
var password         = program.password;
var nodeEnv          = program.node_env || "development";
process.env.NODE_ENV = nodeEnv;

if (!email || !password) {
  program.outputHelp();
  return;
}

if (!tools.validateTools.isEmail(email)) {
  console.log('请输入正确的 email');
  return;
}


var reginfo = {
  email    : email,
  password : password,
  account_type: 9
};


var co             = require('co');
var accountService = require('./services/Account');
var ezmysql        = require('ezway2mysql');
var config         = require('./config');
ezmysql.connect(config.mysql);


console.log("现在开始初始化 cloudarling 系统...");

var fs = require('fs');

console.log('开始创建数据表： ');
fs.readFile('./create.sql', 'utf8', function(err, data) {
  if (err) throw err;
  ezmysql.pool.query(data, null, function (err, rows, fields) {

    var xco = co(function *() {
      var res = yield accountService.register(reginfo);
      console.log(res);
      console.log("你创建的超级管理员帐号是：");
      console.log(`用户名： ${program.email}`);
      console.log(`密码：${program.password}`);
      console.log("现在请按 ^C 退出。");

    }).catch(function (reson) {
      console.log(reson);
      console.log("现在请按 ^C 退出。");
    });
  });
  
});

